[2025-08-24T17:44:23.783+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-24T17:44:23.790+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: churn_pipeline_taskflow.ingestion manual__2025-08-24T16:43:58.310126+00:00 [queued]>
[2025-08-24T17:44:23.791+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: churn_pipeline_taskflow.ingestion manual__2025-08-24T16:43:58.310126+00:00 [queued]>
[2025-08-24T17:44:23.792+0100] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2025-08-24T17:44:23.795+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): ingestion> on 2025-08-24 16:43:58.310126+00:00
[2025-08-24T17:44:23.797+0100] {standard_task_runner.py:64} INFO - Started process 25755 to run task
[2025-08-24T17:44:23.799+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'churn_pipeline_taskflow', 'ingestion', 'manual__2025-08-24T16:43:58.310126+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dag.py', '--cfg-path', '/var/folders/c_/hn2ql5p54ylf2dsc72vqg5h40000gn/T/tmp90klb2vb']
[2025-08-24T17:44:23.801+0100] {standard_task_runner.py:91} INFO - Job 12: Subtask ingestion
[2025-08-24T17:44:23.813+0100] {task_command.py:426} INFO - Running <TaskInstance: churn_pipeline_taskflow.ingestion manual__2025-08-24T16:43:58.310126+00:00 [running]> on host mac.communityfibre.co.uk
[2025-08-24T17:44:23.832+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivam' AIRFLOW_CTX_DAG_ID='churn_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-08-24T16:43:58.310126+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-24T16:43:58.310126+00:00'
[2025-08-24T17:44:23.832+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-24T17:44:23.845+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-24T17:44:23.846+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/homeaccount/PycharmProjects/dmml/churn_prediction_pipeline/airflow_home/dags/airflow_dag.py", line 26, in ingestion
    run_cmd(["python", "scripts/ingest.py"])
  File "/Users/homeaccount/PycharmProjects/dmml/churn_prediction_pipeline/airflow_home/dags/airflow_dag.py", line 13, in run_cmd
    subprocess.run(cmd, check=True)
  File "/Users/homeaccount/miniconda3/envs/churn_pipeline/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'scripts/ingest.py']' returned non-zero exit status 2.
[2025-08-24T17:44:23.849+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=churn_pipeline_taskflow, task_id=ingestion, run_id=manual__2025-08-24T16:43:58.310126+00:00, execution_date=20250824T164358, start_date=20250824T164423, end_date=20250824T164423
[2025-08-24T17:44:23.852+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task ingestion (Command '['python', 'scripts/ingest.py']' returned non-zero exit status 2.; 25755)
[2025-08-24T17:44:23.861+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-24T17:44:23.868+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-24T17:44:23.868+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
